# Use root/example as user/password credentials

version: '2'

services:

    adminer:
        image: adminer
        ports:
            - 8080:8080

    db:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: <dbpass>
        ports:
            - 3306:3306
        command:
            - --wait_timeout=5184000
